---
build_from:
  amd64: python:3.12-slim-bookworm
  aarch64: arm64v8/python:3.12-slim-bookworm
labels:
  org.opencontainers.image.title: Hikvision SDK Bridge
  org.opencontainers.image.source: https://github.com/TimLuist1/hikvision-intercom
